//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cidade_ { get; set; }
        public string Email { get; set; }
        public string Cep_ { get; set; }
        public string Endereco { get; set; }
        public string Pais_ { get; set; }
        public string Usuario { get; set; }
        public string Telefone { get; set; }
        public System.DateTime Data_Nascimento { get; set; }
    }
}
